version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: match-betting-db
    environment:
      POSTGRES_DB: postgres-match-betting-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: hdfhuwe
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    command: [ "redis-server", "--appendonly", "yes"]

volumes:
  postgres-data:
  redis-data: